dist: bionic
language: cpp
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install valgrind libpng-dev libjpeg-dev libxml2-dev libfreetype6-dev libx11-dev lcov -qq
  - pip install --user cpp-coveralls
  - npm install
  - npm install --save-dev @commitlint/travis-cli

before_script:
  - ./node_modules/.bin/commitlint-travis && ./autogen.sh

script:
  - ./configure --enable-gcov && make && make check
  - make
  - make distcheck
  - cd test
  - make
  - ./test
  - ../libtool --mode=execute valgrind --leak-check=full --error-exitcode=42 ./test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
